rf:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 5
  random_state: 42

gb:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 5
  random_state: 42

nn:
  hidden_layer_sizes: [100, 50]
  max_iter: 1000
  random_state: 42

svm:
  kernel: 'rbf'
  C: 1.0
  epsilon: 0.1
